/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    ConnectByEOA: typeof import('./components/connect_flow/ConnectByEOA.vue')['default']
    ConnectByPasskey: typeof import('./components/connect_flow/ConnectByPasskey.vue')['default']
    ConnectModal: typeof import('./components/ConnectModal.vue')['default']
    ConnectModal2: typeof import('./components/connect_flow/ConnectModal.vue')['default']
    ConnectModal3: typeof import('./components/connect_flow/ConnectModal.vue')['default']
    ConnectWallet: typeof import('./components/ConnectWalletStage.vue')['default']
    ConnectWalletStage: typeof import('./components/ConnectWalletStage.vue')['default']
    copy: typeof import('./co./components/connect_flow/ConnectByEOA.vuee')['default']
    EOAStage: typeof import('./components/connect_flow/EOAStage.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    PasskeyStage: typeof import('./components/connect_flow/ConnectByPasskey.vue')['default']
    RadioGroup: typeof import('./components/ui/radio-group/RadioGroup.vue')['default']
    RadioGroupItem: typeof import('./components/ui/radio-group/RadioGroupItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setup: typeof import('./components/connect_flow/Setup.vue')['default']
    SetupSignerStage: typeof import('./components/connect_flow/SetupSignerStage.vue')['default']
  }
}
